name: XMR Mining Setup

on:
  workflow_dispatch:

jobs:
  setup-and-mine:
    runs-on: ubuntu-latest

    steps:
    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

    - name: Clone XMRig repository
      run: |
        git clone https://github.com/xmrig/xmrig.git
        cd xmrig && mkdir build && cd build
        cmake ..
        make -j$(nproc)

    - name: Start Mining
      run: |
        cd xmrig/build
        ./xmrig --url pool.supportxmr.com:443 --user 47EGJLTDXsX2Sm5tBhBtL1HpB9wK1yHtLCq48t59TtbdfSKU5Lj2dutNuvNmyqFP9EUeuGhEJs1vnQjWsCfZAYUs8gSU6v1 --pass x --tls
